version: 2

sources:
  - name: lake_raw          # <- any name you like
    tables:
      - name: admissions
        config:             # <— NEW: adapter-specific config
          external_location: "/Users/vinkels/Code/FederatedCausal/data/20250213_data/clean/admissions_clean.parquet"
          format: parquet   # optional but explicit

      - name: diagnoses
        config:
          external_location: "/Users/vinkels/Code/FederatedCausal/data/20250213_data/clean/diagnoses_clean.parquet"
          format: parquet
