# Nuts Node configuration — Data Station (dev)

strictmode: false
verbosity: debug
datadir: /nuts/data
url: https://nuts-station.localhost

didmethods:
  - web

http:
  internal:
    address: :8081
  public:
    address: :8080

crypto:
  storage: fs

policy:
  directory: /nuts/config/policy

discovery:
  definitions:
    directory: /nuts/config/discovery
