# profiles.yml  – corrected
hospital_lakehouse:
  target: dev
  outputs:
    dev:
      type: duckdb
      # DuckLake catalogue becomes the main database
      path: "ducklake:/Users/vinkels/Code/FederatedCausal/data/ducklake/metadata.ducklake"

      # no attach:  -- remove the boolean
      # no database:  -- default is "main", which is fine

      extensions: ["ducklake", "parquet"]
      threads: 4
